FROM python:3.11

WORKDIR /app

RUN pip install requests beautifulsoup4 pycurl django django-bootstrap5

COPY . .

ENV PYTHONPATH=/app
ENV RUN_MODE=WEB

EXPOSE 8000

CMD ["sh", "-c", "if [ \"$RUN_MODE\" = \"TUI\" ]; then python anime_sama_app/converter/scraper.py; else python manage.py runserver 0.0.0.0:8000; fi"]