services:
  web:
    image: anime_sama_image
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - RUN_MODE=WEB # Set mode to Website
    ports:
      - "8000:8000"
    volumes:
      - app_data:/app

  tui:
    image: anime_sama_image
    environment:
      - RUN_MODE=TUI # Set mode to TUI
    volumes:
      - app_data:/app
    stdin_open: true
    tty: true # Allows interactive terminal for TUI mode

volumes:
  app_data:
